spring:
  application:
    name: datalink-server
  profiles:
    active: dev
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mapper:
  mappers: com.kailaisi.eshopdatalinkservice.config.mapper.CrudMapper
  mapper.not-empty: false
  mapper.identity: MYSQL
logging:
  path: "D:/gongcheng/web/eshop-datalink-service/log/"
  file: "weblog.log"
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml