server:
  port: 8767
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: datalink-server
  datasource:
    username: root
    password: 03102896528
    url: jdbc:mysql://localhost:3306/eshop
logging:
  path: "D:/gongcheng/web/eshop-datalink-service/log/"
  file: "weblog.log"
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
mapper:
  mappers:
    - com.kailaisi.eshopdatalinkservice.config.mapper.MyMapper
  not-empty: true