server:
  port: 8767
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.1.11:3307/mall?serverTimezone=UTC
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall,log4j
  redis:
    host: 192.168.1.5
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000
  data:
      mongodb:
        host: 192.168.1.5 # mongodb的连接地址
        port: 27017 # mongodb的连接端口号
        database: mall-port # mongodb的连接的数据库
      elasticsearch:
        cluster-name: elasticsearch
        cluster-nodes: 192.168.1.11:9300
  main:
    allow-bean-definition-overriding: true

