server:
  port: 8767
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: datalink-server
logging:
  path: "D:/gongcheng/web/eshop-datalink-service/log/"
  file: "weblog.log"