---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wu.
--- DateTime: 2019/12/28 22:21
---
-- 函数：尝试获得红包，如果成功，则返回json字符串，如果不成功，则返回空
-- KEYS 用户ID
-- 参数：红包队列名， 已消费的队列名，去重的Map名，
-- 返回值：nil 或者 json字符串，包含用户ID：userId，红包ID：id，红包金额：money
-- 如果用户已抢过红包，则返回nil

if redis.call("hexists", ARGV[3], KEYS[1]) ~= 0 then
    print("nil")
    return nil
else
    local x = {};
    -- 先取出一个小红包
    local hongBao = redis.call('rpop', ARGV[1]);
    local re = cjson.encode(x);
    x['userId'] = KEYS[1];
    re = cjson.encode(x);
    if hongBao then
        x["money"] = tonumber(hongBao)
        -- 加入用户ID信息
        -- 把用户ID放到去重的set里
        re = cjson.encode(x);
        redis.call('hset', ARGV[3], KEYS[1], KEYS[1]);
        -- 把红包放到已消费队列里
        redis.call('lpush', ARGV[2], re);
        return re;
    else
    end
    return re
end
